# Generated by Django 4.0.3 on 2022-04-11 09:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0002_newfollowing_delete_following"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewFollowing",
            new_name="Following",
        ),
    ]
