# Generated by Django 4.0.3 on 2022-03-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
