# Generated by Django 4.0.3 on 2022-04-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_newfollowing_following"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
