# Generated by Django 4.0.3 on 2022-04-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_follows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
    ]
