# Generated by Django 4.0.3 on 2022-04-04 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='drooling_faces',
            field=models.ManyToManyField(related_name='post_drooling_faces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='loves',
            field=models.ManyToManyField(related_name='post_loves', to=settings.AUTH_USER_MODEL),
        ),
    ]
