# Generated by Django 4.0.3 on 2022-04-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_options_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=80),
        ),
    ]
