# Generated by Django 4.0.3 on 2022-04-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_favorite_posts'),
        ('post', '0003_alter_post_title'),
    ]

    operations = [
    ]
