# Generated by Django 4.0.3 on 2022-04-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_drooling_faces_post_likes_post_loves'),
        ('post', '0003_post_drooling_faces_post_loves'),
    ]

    operations = [
    ]
