# Generated by Django 4.0.3 on 2022-04-11 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_merge_20220411_1515'),
        ('post', '0004_post_favorite_posts'),
    ]

    operations = [
    ]
