# Generated by Django 4.0.3 on 2022-04-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_merge_20220411_1931'),
        ('post', '0005_merge_20220412_0821'),
    ]

    operations = [
    ]
